### ISSUE TITLE
Add Push Notification Entitlement in iOS app for CMS

### ISSUE THREAD

**Issue by wilfredstegeman** [schedjoules/iOS-SDK#3]
Our app registers with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, enable Push Notifications in the project editor's Capabilities pane as follows:

1. In the Project Navigator, select your project.
2. In the editor, select your iOS app target.
3. Select the Capabilities tab.
4. Enable the Push Notifications capability. 

<img width="680" alt="push_notification_capability_2x" src="https://cloud.githubusercontent.com/assets/5968782/23746290/b05682a0-04bb-11e7-9acd-ed4216aeb499.png">

Xcode adds the needed entitlements to your project.

**Comment by rutgerg** [comment]
Issue moved to [schedjoules/backlog #154](https://github.com/schedjoules/backlog/issues/154) via [**ZenHub**](https://www.zenhub.com/)
