### ISSUE TITLE
Add value to privacy key

### ISSUE THREAD

**Issue by wilfredstegeman** [schedjoules/iOS-SDK#4]
Add the following value:
This app needs access to the calendar to update events.

<img width="1019" alt="screenshot 2017-03-09 11 45 28" src="https://cloud.githubusercontent.com/assets/5968782/23746885/e8c67e86-04bd-11e7-82a8-1c7a9f450205.png">

**Comment by rutgerg** [comment]
Issue moved to [schedjoules/backlog #153](https://github.com/schedjoules/backlog/issues/153) via [**ZenHub**](https://www.zenhub.com/)
