### ISSUE TITLE
School Holiday App icons for iOS

### ISSUE THREAD

**Issue by dmfs** [schedjoules/iOS-SDK#5]
@wilfredstegeman commented on [Fri Nov 03 2017](https://github.com/schedjoules/android-event-discovery-sdk/issues/432)

---

@rutgerg commented on [Mon Nov 06 2017](https://github.com/schedjoules/android-event-discovery-sdk/issues/432#issuecomment-342073759)

I don't see icon at https://london.schedjoules.com/apps/412/edit?locale=en yet. Where did you put them?

---

@wilfredstegeman commented on [Mon Nov 06 2017](https://github.com/schedjoules/android-event-discovery-sdk/issues/432#issuecomment-342083126)

I uploaded them to a new folder apps/1295121238/

---

@rutgerg commented on [Mon Nov 06 2017](https://github.com/schedjoules/android-event-discovery-sdk/issues/432#issuecomment-342102207)

To staging; not production. I just deployed to production

---

@rutgerg commented on [Mon Nov 06 2017](https://github.com/schedjoules/android-event-discovery-sdk/issues/432#issuecomment-342103347)

Sizes like Default-568h@2x~iphone and Default@2x~iphone and couple of others are not needed anymore?

---

@wilfredstegeman commented on [Mon Nov 06 2017](https://github.com/schedjoules/android-event-discovery-sdk/issues/432#issuecomment-342111060)

The default images were opening screens that we don't use anymore indeed. Do you miss any icons as well or only these default images?

**Comment by rutgerg** [comment]
Issue moved to [schedjoules/general-issues #220](https://github.com/schedjoules/general-issues/issues/220) via [**ZenHub**](https://www.zenhub.com/)
